
name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/MLForensics/MLForensics-farzana/FAME-ML" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest bandit pandas numpy

    - name: Run Tests
      run: |
        pytest --junitxml=test-results.xml

    - name: Run Fuzzing
      run: |
        python fuzz.py

    - name: Static Analysis with Bandit
      run: |
        bandit -r .
